version: '3.8'

services:
  web-server:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./web-server:/app
    environment:
      - KAFKA_URL=http://producer:8000/
      - ELASTICSEARCH_URL=http://es-server:9000/
    depends_on:
      - kafka
    networks:
      - dyte-network

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - dyte-network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CLIENT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,CLIENT://kafka:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - dyte-network

  cassandra:
    image: bitnami/cassandra:latest
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_KEYSPACE=dyte
    healthcheck:
      test:
        [
          'CMD',
          'cqlsh',
          '-u',
          'cassandra',
          '-p',
          'cassandra',
          '--execute',
          'SELECT * FROM system_schema.tables;',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - dyte-network

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    command: sh -c "while ! timeout 1 bash -c '</dev/tcp/cassandra/9042'; do sleep 1; done && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./consumer:/app
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=dyte
      - CASSANDRA_CONTACT_POINTS=cassandra
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
    depends_on:
      - kafka
      - zookeeper
      - cassandra
    networks:
      - dyte-network

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 4000:8000
    volumes:
      - ./producer:/app
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    depends_on:
      - kafka
      - zookeeper
      - cassandra
    networks:
      - dyte-network

  elasticsearch:
    image: bitnami/elasticsearch:7
    container_name: elasticsearch
    ports:
      - '9200:9200'
    environment:
      - ELASTICSEARCH_ADVERTISED_HOSTNAME=elasticsearch
      - ELASTICSEARCH_ADVERTISED_PORT_NUMBER=9200
      - ELASTICSEARCH_ALLOW_REMOTE_CONNECTIONS=yes
    networks:
      - dyte-network

  es-server:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9000
    volumes:
      - ./elasticsearch:/app
    networks:
      - dyte-network

  kibana:
    image: bitnami/kibana:7
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - KIBANA_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - dyte-network

networks:
  dyte-network:
    driver: bridge
